# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\persion\project_client\UI\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_bg_of_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_bg_of_login.setGeometry(QtCore.QRect(0, 0, 350, 500))
        self.lbl_bg_of_login.setObjectName("lbl_bg_of_login")
        self.lgl_title_of_app = QtWidgets.QLabel(self.centralwidget)
        self.lgl_title_of_app.setGeometry(QtCore.QRect(550, 0, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.lgl_title_of_app.setFont(font)
        self.lgl_title_of_app.setObjectName("lgl_title_of_app")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(510, 470, 141, 23))
        self.btn_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_register.setObjectName("btn_register")
        self.btn_login_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login_close.setGeometry(QtCore.QRect(770, 0, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setBold(True)
        font.setWeight(75)
        self.btn_login_close.setFont(font)
        self.btn_login_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login_close.setObjectName("btn_login_close")
        self.edit_pwd_of_user = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_pwd_of_user.setGeometry(QtCore.QRect(461, 192, 221, 31))
        self.edit_pwd_of_user.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_pwd_of_user.setObjectName("edit_pwd_of_user")
        self.edit_name_of_user = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_name_of_user.setGeometry(QtCore.QRect(461, 143, 221, 31))
        self.edit_name_of_user.setText("")
        self.edit_name_of_user.setObjectName("edit_name_of_user")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(461, 252, 221, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.chk_remember_me = QtWidgets.QRadioButton(self.splitter)
        self.chk_remember_me.setObjectName("chk_remember_me")
        self.btn_confrim_login = QtWidgets.QPushButton(self.splitter)
        self.btn_confrim_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_confrim_login.setObjectName("btn_confrim_login")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edit_name_of_user, self.edit_pwd_of_user)
        MainWindow.setTabOrder(self.edit_pwd_of_user, self.btn_confrim_login)
        MainWindow.setTabOrder(self.btn_confrim_login, self.btn_register)
        MainWindow.setTabOrder(self.btn_register, self.chk_remember_me)
        MainWindow.setTabOrder(self.chk_remember_me, self.btn_login_close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_bg_of_login.setText(_translate("MainWindow", "背景图片"))
        self.lgl_title_of_app.setText(_translate("MainWindow", "金融风暴"))
        self.btn_register.setText(_translate("MainWindow", "没有账号？去注册"))
        self.btn_login_close.setText(_translate("MainWindow", "X"))
        self.edit_pwd_of_user.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.edit_name_of_user.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.chk_remember_me.setText(_translate("MainWindow", "记住密码"))
        self.btn_confrim_login.setText(_translate("MainWindow", "登录"))
